// <auto-generated />
using System;
using LibrarySystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystemAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrarySystemAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AvailabilityStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Edition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Pascal Zury",
                            AvailabilityStatus = true,
                            Edition = "Tenth Edition",
                            Genre = "Science",
                            PublicationDate = new DateTime(1945, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Linear Data Structures, Non Linear Data Structures",
                            Title = "Introduction to Data Structures"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Eric Zury",
                            AvailabilityStatus = true,
                            Edition = "Eleventh Edition",
                            Genre = "Engineering",
                            PublicationDate = new DateTime(1955, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Signals, Controls",
                            Title = "Introduction to Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Pascal Zury",
                            AvailabilityStatus = true,
                            Edition = "First Edition",
                            Genre = "Science",
                            PublicationDate = new DateTime(1925, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Objects and Classes in C#",
                            Title = "Introduction to C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
